In [2]:
import numpy as np

# 建立矩陣 create matrix 1d

In [3]:
np_data = np.array([1,2,3,4])

In [4]:
np_data

array([1, 2, 3, 4])

# 對矩陣內的元素運算 element operation

In [5]:
np_data + np_data

array([2, 4, 6, 8])

In [6]:
np_data - np_data

array([0, 0, 0, 0])

In [7]:
np_data * np_data

array([ 1,  4,  9, 16])

In [8]:
np_data / np_data

array([ 1.,  1.,  1.,  1.])

In [9]:
np_data * 0.5

array([ 0.5,  1. ,  1.5,  2. ])

In [10]:
np_data[2]

3

In [11]:
np_data[:2]

array([1, 2])

# 建立矩陣 muti-dim

In [12]:
np_data = np.array([[1,2,3,4], [1,3,5,7], [2,4,6,8]])

In [13]:
np_data

array([[1, 2, 3, 4],
       [1, 3, 5, 7],
       [2, 4, 6, 8]])

In [14]:
np_data + np_data

array([[ 2,  4,  6,  8],
       [ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [15]:
np_data * np_data

array([[ 1,  4,  9, 16],
       [ 1,  9, 25, 49],
       [ 4, 16, 36, 64]])

In [16]:
np_data - np_data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np_data / np_data

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
np_data[2]

array([2, 4, 6, 8])

In [19]:
np_data[2][0]

2

In [20]:
np_data[:2]

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

In [21]:
np.absolute(np_data * -0.5)

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 0.5,  1.5,  2.5,  3.5],
       [ 1. ,  2. ,  3. ,  4. ]])

In [22]:
np_data

array([[1, 2, 3, 4],
       [1, 3, 5, 7],
       [2, 4, 6, 8]])

# 統計運算 statistic operation

In [23]:
np.sqrt(np_data)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 1.        ,  1.73205081,  2.23606798,  2.64575131],
       [ 1.41421356,  2.        ,  2.44948974,  2.82842712]])

In [24]:
np.log(np_data)

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436],
       [ 0.        ,  1.09861229,  1.60943791,  1.94591015],
       [ 0.69314718,  1.38629436,  1.79175947,  2.07944154]])

In [25]:
np_data.mean()

3.8333333333333335

In [26]:
np_data.std()

2.1921577396609844

In [27]:
np_data.sum()

46

In [28]:
np_data[0].mean()

2.5

# 矩陣運算 matrix operation

In [30]:
matrix1 = np.array([[1,2,3],[2,4,6]])

In [31]:
matrix1

array([[1, 2, 3],
       [2, 4, 6]])

In [32]:
matrix2 = np.array([[0,0,0],[1,1,1]])

In [33]:
matrix2

array([[0, 0, 0],
       [1, 1, 1]])

In [34]:
matrix1 * matrix2

array([[0, 0, 0],
       [2, 4, 6]])

In [35]:
matrix2.transpose()

array([[0, 1],
       [0, 1],
       [0, 1]])

In [36]:
np.dot(matrix1, matrix2.transpose())

array([[ 0,  6],
       [ 0, 12]])